### ISSUE TITLE
Add ability to configure provisioned iops assigned to EBS volumes

### ISSUE THREAD

**Issue by antoineserrano** [sky-uk/clusterverse#107]
See https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_vol_module.html#parameter-iops

- Should be omitted unless configured specifically by users
- Should live in global `cluster_vars.yml`
- Requires documentation and examples to be updated

**Comment by citrocity** [comment]
https://github.com/sky-uk/clusterverse/pull/112

**Comment by citrocity** [comment]
Complete
