### ISSUE TITLE
Add support for external inputs in Filebeat

### ISSUE THREAD

**Issue by flfernandez** [sky-uk/clusterverse#109]
As part of application log ingestion into TOP (i.e. Cassandra and Couchbase), it would be great to have the ability of adding external inputs in Filebeat.

Ref: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-reloading.html

I therefore created this branch with a small addition in the filebeat template `config/templates/etc/filebeat/filebeat.yml.j2`:

https://github.com/sky-uk/clusterverse/tree/filebeat_ext_inputs

**Comment by flfernandez** [comment]
I also found an issue on line 33 of the filebeat template:

```
{% if beats_config.filebeat.extra_logs_paths %}
```
should be:
```
{% if beats_config.filebeat.extra_logs_paths is defined %}
```

So that the variable `beats_config.filebeat.extra_logs_paths` can be optional.

**Comment by antoineserrano** [comment]
@flfernandez it would be a great addition, please don't hesitate to raise a PR when your tests are ok :)

**Comment by flfernandez** [comment]
Thanks @antoineserrano 
Created PR: https://github.com/sky-uk/clusterverse/pull/110

**Comment by antoineserrano** [comment]
PR merged, closing this issue.
