### ISSUE TITLE
GCP DNS domain support

### ISSUE THREAD

**Issue by leslieonline27** [sky-uk/clusterverse#21]
This looks to be missing functionality for GCP.  DNS provisioning and configuration should be at the same level as for AWS (or across any other cloud provider).

I am happy to contribute this back with a PR

**Comment by sky-amoncadot** [comment]
Hi @leslieonline27, @kristian-shaw  and I are currently working on building `Cloud DNS` functionality within Clusterverse so GCP records can be automated. 

We will update this issue with more information once we have progressed 👍

**Comment by sky-amoncadot** [comment]
Hi @leslieonline27 . Please see #26 for further information on this request

**Comment by sky-amoncadot** [comment]
@leslieonline27 The Cloud DNS functionality is also required for the roles that the playbook `redeploy.yml` calls. Working on this at the moment and have factored in the 1/3 PRs:

#33

**Comment by dseeley-sky** [comment]
Please can you check the latest?  A lot of GCP DNS fixes went into https://github.com/sky-uk/clusterverse/pull/47.

**Comment by dseeley-sky** [comment]
More functionality in https://github.com/sky-uk/clusterverse/pull/68
