### ISSUE TITLE
systemd-run argument only available from Ubuntu 18.04

### ISSUE THREAD

**Issue by flfernandez** [sky-uk/clusterverse#32]
The systemd-run argument "--wait" is only available from Ubuntu 18.04.

Therefore it fails against Ubuntu 16.04 as per below:

`
TASK [clusterverse/config : Wait for any possibly running unattended upgrade to finish] ****************************
fatal: [mycluster-dev-sys-c0-1582713112]: FAILED! => {"changed": true, "cmd": ["systemd-run", "--property=After=apt-daily.service apt-daily-upgrade.service", "--wait", "/bin/true"], "delta": "0:00:00.021216", "end": "2020-02-26 10:33:57.552404", "msg": "non-zero return code", "rc": 1, "start": "2020-02-26 10:33:57.531188", "stderr": "systemd-run: unrecognized option '--wait'", "stderr_lines": ["systemd-run: unrecognized option '--wait'"], "stdout": "", "stdout_lines": []}
`

Ref:
Ubuntu 18.04 LTS: http://manpages.ubuntu.com/manpages/bionic/man1/systemd-run.1.html
Ubuntu 16.04 LTS: http://manpages.ubuntu.com/manpages/xenial/man1/systemd-run.1.html

**Comment by dseeley-sky** [comment]
Fixed by #36
