### ISSUE TITLE
Automated testing suite

### ISSUE THREAD

**Issue by leslieonline27** [sky-uk/clusterverse#37]
To assist with approving changes, it would be ideal to have a fully automated testing suite which runs against new commits to an incoming PR branch.  It should test all supported clouds and distros, so `aws` and `gcp` and across `ubuntu` and `centos` in each:

- deploy
- redeploy
- rollback
- canary start/finish

As a start we'll probably need to decide:

- where will these tests run? (CircleCI has been initially identified)
- do we also want to include any linting / syntax tests?
- who will be notified of successful / failed tests?

**Comment by eolix** [comment]
We were discussing exactly this today, the scope as you described.
CircleCI seems like a good alternative (and might provide a publicly-accessible endpoint), but we need to establish environments and locations in both cloud providers.

Definitely linting and syntax testing as well.

Should we have an internal Slack channel for notifications?

**Comment by leslieonline27** [comment]
> CircleCI seems like a good alternative (and might provide a publicly-accessible endpoint), but we need to establish environments and locations in both cloud providers.

I believe @antoineserrano was checking out our access yesterday

> Should we have an internal Slack channel for notifications?

 Yeah I think so, and a badge on the repo I reckon
